export const CLIENT_SERVICES_API = 'http://localhost:8882/api/client-services';

//ACTIONS
export const FETCH_CLIENT_SERVICES = 'FETCH_CLIENT_SERVICES';
export const RECEIVE_CLIENT_SERVICES = 'RECEIVE_CLIENT_SERVICES';
export const ERROR_IN_FETCH_CLIENT_SERVICES = 'ERROR_IN_FETCH_CLIENT_SERVICES';

export const FETCH_SLIDE_SHOW = 'FETCH_SLIDE_SHOW';
export const RECEIVE_SLIDE_SHOW = 'RECEIVE_SLIDE_SHOW';
export const ERROR_IN_FETCH_SLIDE_SHOW = 'ERROR_IN_FETCH_SLIDE_SHOW';