-   request:
        url: /api/optional-products
        latency: 3000
    response:
        headers:
            content-type: application/json
        file: optionalProducts.json

-   request:
        url: /api/opSlider
        latency: 3000
    response:
        headers:
            content-type: application/json
        file: optionalProductsSlider.json


# // [
# //   {
# //     "request":{
# //       "url" : "/api/optional-products",
# //       "latency":3000
# //     },
# //     "response" : {
# //       "headers" : {
# //         "content-type" : "application/json"
# //       },
# //       "file" : "optionalProducts.json"
# //     }
# //   } 
# // ]