//URL API
export const OPTIONAL_PRODUCTS_API = 'http://localhost:8882/api/optional-products';
export const OPTIONAL_PRODUCTS_SLIDE_SHOW = 'http://localhost:8882/api/opSlider';

//ACTIONS
export const FETCH_OPTIONAL_PRODUCTS = 'FETCH_OPTIONAL_PRODUCTS';
export const RECEIVE_OPTIONAL_PRODUCTS = 'RECEIVE_OPTIONAL_PRODUCTS';
export const ERROR_IN_FETCH_OPTIONAL_PRODUCTS = 'ERROR_IN_FETCH_OPTIONAL_PRODUCTS';

export const FETCH_SLIDE_SHOW = 'FETCH_SLIDE_SHOW';
export const RECEIVE_SLIDE_SHOW = 'RECEIVE_SLIDE_SHOW';
export const ERROR_IN_FETCH_SLIDE_SHOW = 'ERROR_IN_FETCH_SLIDE_SHOW';
